### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by gazhayes** [TheJoin95/covid19-market-waiting-times#15]
Hello from New Zealand.

Great project, just wanted to let you know about my (different) approach to solving the same problem, in case it helps you somehow: https://github.com/howlongistheline/howlongistheline.org

**Comment by TheJoin95** [comment]
Hello,
thank you for sharing your idea, how is it going?

Actually I'm ready to release a crowdsourcing feature to also have a feedback from the final user about lines.
