### ISSUE TITLE
To support real-time wait times, allow for input from those actually inline

### ISSUE THREAD

**Issue by neiljthomson** [TheJoin95/covid19-market-waiting-times#16]
Average wait times is not particularly useful. The key is data that is no more than 60 minutes olde.

While the longer term solution would be a smartphone app, a short term fix would be a web site that is "responsive"/optimized for smartphone where someone who has finished their "wait" in line can input the time and location of the store.

**Comment by TheJoin95** [comment]
Hi,
thank you for your feedback.

This morning I released this feature:
![image](https://user-images.githubusercontent.com/6616203/79643380-f3038280-81a2-11ea-926e-fdc1450b9ade.png)

The idea behind it is the same: get a real feedback from who is in the line.
Actually the website is responsive and provide also a PWA (=Progressive Web App).

An application need to be updated to get all these features, meanwhile a Web App no.
In the next future an App would be probably the best fit for this project, as you also said.

Now I'm developing a lot of feature and I need to get a lot of feedback and for these reason I think that the web is the right choice.

**Comment by neiljthomson** [comment]
LOL - did't try it this morning - exactly what I wanted. Very Good.
