### ISSUE TITLE
Shoppers Drug Mart

### ISSUE THREAD

**Issue by hassanm1** [TheJoin95/covid19-market-waiting-times#17]
Hi my store shoppers drug mart on Guelph St in Sinclair perpetually showing line of 20min when there is no line

**Comment by hassanm1** [comment]
Sorry Guelph St and Sinclair Avenue in Georgetown Ontario Canada

**Comment by TheJoin95** [comment]
Hi,
thank you for your feedback.
The waiting time are estimated.
The estimation is based on previous data, so it can may be not too accurate.

By clicking on your place marker you can always set the real waiting time.

I hope it can be useful.
Thank you
