### ISSUE TITLE
Showing multiple tags for a location - one of which is the wrong location

### ISSUE THREAD

**Issue by neiljthomson** [TheJoin95/covid19-market-waiting-times#18]
Have a bug here in Kanata, Ontario, Canada.

The tag ("1") has the right store name (Loblaws), but the address is for a different store (WalMart), which is many kilometers away. I see why, the Canadian Postal code is wrong (K2T 1B6 is wrong. The postal code should be K2S 1B6 (T->S)). Looks like incorrect information somewhere in the data.

The tag ("2") is correct (store, address, etc.)

Attaching screen shots with "1" and "2" identified
![Tag at correct location](https://user-images.githubusercontent.com/12633943/79644071-8a051600-8174-11ea-875f-6f5782e4ca56.png)
![Tag at wrong location](https://user-images.githubusercontent.com/12633943/79644072-8a9dac80-8174-11ea-95c9-42f536c8c6fd.png)
![2 tags one location](https://user-images.githubusercontent.com/12633943/79644074-8a9dac80-8174-11ea-8e30-0f2267c07ae8.png)

**Comment by TheJoin95** [comment]
Thank you for report me this issue.
I will dig into it and let you know.
