### ISSUE TITLE
Multiple "Venues" for Walmart Supercentre in Orleans.

### ISSUE THREAD

**Issue by HeyWha** [TheJoin95/covid19-market-waiting-times#19]
There are three "venues" for Walmart Supercentre in Orleans ON:

1.  Walmart Orleans Supercentre
3900 Innes Rd, Orléans, ON K1W 1K9, Canada

2.  Walmart Supercentre
3900 Innes Rd, Orléans, ON K1W 1K9, Canada

3.  SmartCentres Orleans II
3900 Innes Rd, Orléans, ON K1C 1T1, Canada

If I were to keep one, I'd keep #2.

![WalmartX3Orleans](https://user-images.githubusercontent.com/63923857/79645205-d4d65c00-817b-11ea-9675-f827f794f9a2.png)

**Comment by TheJoin95** [comment]
Thank you,
I will look into it.

These are the data that comes from Google, but I will try to fix it my side.
