### ISSUE TITLE
The legend counter need a description

### ISSUE THREAD

**Issue by nanny07** [TheJoin95/covid19-market-waiting-times#2]
Hi and thanks you for your project.

I think it's difficult to understand the meaning of the numbers:

![image](https://user-images.githubusercontent.com/17173586/78122199-b26ae180-740c-11ea-918e-be8897150239.png)

Is it the numbers of peoples in queue or the hypothetical waiting time?

Reading the code I've got my answer but for the common people is not that easy to understand

**Comment by TheJoin95** [comment]
Hi, thank you for your feedback, I appreciate it!

Yes, the legend has not a unit measure, that is bad.
I will add a label on top or bottom of it, indicating the range of waiting time in minutes

Again, thank you for notice me ;)
