### ISSUE TITLE
Costco Richmond Hill is missing

### ISSUE THREAD

**Issue by leprechaun1** [TheJoin95/covid19-market-waiting-times#20]
https://www.google.com/maps/place/Costco+Wholesale/@43.9016471,-79.3907923,15z/data=!4m5!3m4!1s0x0:0xcf90cc3b45542ac1!8m2!3d43.9016471!4d-79.3907923

Please add it.

**Comment by TheJoin95** [comment]
Hi,

unfortunately I do not have any information about time spent and popolartimes for that place.
In the next realease it would be possibile to add a new place, but actually you can only search for an alraedy added place

Thank you for your feedback
