### ISSUE TITLE
tag is on wrong location

### ISSUE THREAD

**Issue by iaskyouwhynotme** [TheJoin95/covid19-market-waiting-times#21]
Bethune Memorial House on John St North in Gravenhurst Ontario is tagged on the wrong location.  
It should be across the street (kitty-corner from the Gravenhurst Curling Club).
The correct location is even marked with the National Historic Site icon.
Please rectify.  Thank-you.

**Comment by TheJoin95** [comment]
Hi,

is the place on the map?
Because I think that is not a market/store/bakery and it will not popup on the map.
Am I right? 

Anyway, can you please provide me a screenshot?
Thank you

**Comment by iaskyouwhynotme** [comment]
Yes, the place is on the map as well as lots of other places that are not markets, stores or bakeries.  I've tried taking a screen shot, but no luck.  I have Windows10 on my computer and apparently there is a problem with the clipboard feature.  I never take screenshots of anything, so did not know about this issue and am not interested in attempting to fix it.   
Thanks for trying anyways.
This webiste is, in general, a good idea and is quite useful.

**Comment by TheJoin95** [comment]
I will dig into it.
Thank you for your precious feedback
