### ISSUE TITLE
Hosting and Infrastructure

### ISSUE THREAD

**Issue by 604tech** [TheJoin95/covid19-market-waiting-times#22]
Hi,

We are a technology consultant company here in Canada and we came across your project. Is there anything we could do to help you distribute the hosting for this project through to a server here in Canada? You mentioned you are a bit limited where you are hosting. 

Cheers

**Comment by TheJoin95** [comment]
Hi,

thank you for your support.
The last couple of week I made some changes on the server side and I optimized a lot of things.
Now I've got two little VPS that are running one in Europe and one in NY area and with those VPS I can still manage a 100K users/day.

If this number will increase drastically, can I contact you here?

Thank you

**Comment by 604tech** [comment]
Yes for sure

**Comment by 604tech** [comment]
Yes for sure
