### ISSUE TITLE
bg-33min wait time for some places

### ISSUE THREAD

**Issue by colonelchlorine** [TheJoin95/covid19-market-waiting-times#26]
When a place has a wait time that is not rounded to the nearest 5 or 10, it doesn't show properly in the UI. I was going to update the CSS, but I think this is more rooted around the `getWaitTime` function. If CSS only supports increments of 5, then this function should do the rounding as well for the `meanTimeSpent` value.

![image](https://user-images.githubusercontent.com/1085938/79778423-b3ee4200-8306-11ea-876d-cb834baf24de.png)

**Comment by colonelchlorine** [comment]
I see there is a fair amount of code in there for rounding and it depends on a few factors (popularity, time of day, etc).

See there's a bunch of Math.ceil / 5 * 5 rounding, but this one place could be an issue. The `meanTimeSpent` doesn't have any rounding applied so can throw it off the 5 increments. Just a hunch.

```
} else if (diffPopTimes > 0 && diffPopTimes < (popTimes / 5)) {
    increase = meanTimeSpent;
} else if (diffPopTimes >= (popTimes / 5) && diffPopTimes <= (popTimes / 2.9)) {
```

**Comment by TheJoin95** [comment]
Hi,
thank you for point this out.
That function need a refactoring and by doing it I will fix this issue.
The code is not too much readable, I do not like it.
That's why.

Again, thank you for your previous feedback! :)

Feel free to open other issue ;)

**Comment by TheJoin95** [comment]
Fixed in the last commit,
thank you
