### ISSUE TITLE
Function to add or update locations

### ISSUE THREAD

**Issue by EvilSupahFly** [TheJoin95/covid19-market-waiting-times#29]
There's a very popular store near me which isn't on the map, and I was hoping you could add a way to suggest new locations, either in the "Not Found" results box, or by clicking (or long-tapping for mobiles) on the map.

**Comment by TheJoin95** [comment]
Hi,

yes, I'm working to make this possible.
I received a lot of feedback about this issue.

I hope to release it in the next few days

**Comment by EvilSupahFly** [comment]
Awesome! Great work, by the way!

**Comment by TheJoin95** [comment]
Can you check it today?
I removed the filter, so now you should search/see your place on the map.
It will be a blue marker, because I did not receive any information about the time spent or the populartimes for these places.

Let me know,
thank you

**Comment by TheJoin95** [comment]
Thank you for the feedback.

From your screenshot I can see that some buttons are missing from the UI.
I think that something is being cached: can you try to refersh/remove the cache? Or can you try to visit the website instead of using the app?

This morning I released a new version of UI/UX.

Thank you

**Comment by EvilSupahFly** [comment]
I cleared the cache on my phone's browser and everything looks good now. Thanks!

![Screenshot_20200423-102056](https://user-images.githubusercontent.com/3280846/80110122-56e3cd80-854c-11ea-9c55-47da6b9080e5.png)

**Comment by TheJoin95** [comment]
Hooray!
I'm still working on it, but in these days I'll monitor this feature.
I'm gonna close this issue, feel free to reopen.

Consider to give a star to this project as a method for support me!
Thank you for your precious feedback
