### ISSUE TITLE
Refactoring UI/UX

### ISSUE THREAD

**Issue by danieldafoe** [TheJoin95/covid19-market-waiting-times#9]
Hey there! First off, I really like the usefulness of the application. Great work! I heard about it on a popular site in Toronto called **blogto.com**.

I took a look at your list of TODOs and I was wondering what you guys looking to do for the refactoring of UI/UX? A couple things I think the front end could benefit from are:

1. Sass (https://sass-lang.com). This would give the immediate benefit of being able to separate your CSS into separate files for easier maintainability and keeping things cleaner. I see there's a grunt package for easily adding Sass to a grunt project (https://www.npmjs.com/package/grunt-sass). 

2. A clear folder structure for code that developers work on (pre-compiled) and another place where the generated files get placed (minified/compiled files). Having something like a `src/` folder and a `dist/` folder would be great start. It would only take the modification of a couple things in your gruntfile.

3. Improvements to the accessibility of the website. There are a few minor things that could be done to improve the ability for people with certain disabilities to use your great application! This web application would be beneficial to them as well, so let's help them be able to use it. 🙂

4. Tiny UI improvements. Things like:
- your rating stars being cut off on the top,
- icons in your circle buttons in the top right and bottom right corners being off-center,
- consistent spacing between/around elements in your interface,
- a banner/logo at the top or side to inform people what they're looking at

I would be happy to start with these things if you would like the help!

**Comment by TheJoin95** [comment]
Hi Daniel,
thank you for notice the long todo list :)

Yes, you are right about all the 4 points.
The accessibility is less than 10 points for Google, and it is not good, as the others point.

The refactoring of UI/UX mean also to add some new features and to change some things like: -- the prompt on the search button and on geoerror function
- add a modal popup on the map marker, Google style
- add an autocomplete box on searching an address/city/place name
- add a "splashscreen modal" with the project infos, at the first user visit on the map
- change folder structure

Any help is appreciated!
Thank you for your precious feedback

**Comment by danieldafoe** [comment]
OK, got it. I'll open up some small PRs this evening like separating your CSS into multiple files, some accessibility enhancements, and folder structure.

What would you like me to work on first out of the other UI enhancements? The splash screen? Autocomplete?

Also, what do you mean by the modal pop-up map marker "Google style"? Do you mean the blue part I circled or the red part in the screen shot below?
 
<img width="1920" alt="screen shot of Google Maps showing a map marker modal and a side bar" src="https://user-images.githubusercontent.com/6425338/79142056-ea691180-7d88-11ea-8905-0981958d8208.png">

**Comment by TheJoin95** [comment]
Thank you, I really appreciate it!

I think that a prior UI enhancement would be the splash screen because when you enter for the first time on the page you do not know what it talk about.
As you said, also a simple logo could be helpful.

> the modal pop-up map marker "Google style"?

Yes, I'm sorry for not being explicit. I mean a simple version of the red circled part, without the image.
I was also thinking that the popup, on mobile devices, could open in full page, like in the Google Maps app.

Because one of my future goal is to enable the user to give a realtime feedback about the line.
E.g. I'm in line for a Walmart Center and I see that there are at least 45 people before my turn. I noticed that the Map is giving me an estimated waiting time of 30min while the correct estimate would be, e.g., 50min. So an user can report how many persons are in line and realign the estimate.

I hope I explained myself.
Again, thank you for the support.

**Comment by danieldafoe** [comment]
OK, so you want me to do the splash screen first? Before the other stuff?

 No need to apologize! I just want to make sure I am building how you envision it. I think I get what you mean now, thank you.

That would be a great future goal! Hopefully I can help with that in the future as well. Have you considered using GitHub Projects in order to organize what you want to do now, what's in progress, and create your list of TODOs there?

**Comment by TheJoin95** [comment]
Yes, you are right: splash screen first, if you agree :)

Yes, I was considering to use Projects to organize better the whole repository.
In these days I needed to optimize the backend side, testing some VPS, due the high traffic that the Map has started to receive.

So I left some things behind, like the UI/UX, and the project structure.
When I do not work I will update also these important aspect, to let other dev like you comes to help :)

**Comment by danieldafoe** [comment]
Do you use `index.gen.html` at all? It doesn't seem like the `processhtml` grunt command works properly. I've been trying for a while to get it to work but it seems like you just use a processed and minified HTML file.

**Comment by elina-codes** [comment]
Hey @TheJoin95,

If you'd like another hand I'd love to help out! UX/UI is my bread and butter. @danieldafoe I'd be happy to follow your lead and/or make suggestions, whatever you'd like.

**Comment by danieldafoe** [comment]
@elina-codes That sounds great! Sorry I didn't see this sooner, I don't tend to click on my notification bell. 😅 

Could you join our Slack so we can all align? https://join.slack.com/t/covid19-waiting-times/shared_invite/zt-du25lag0-3Q6Iwxuy9Qdd~5YfovbNjg
